# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Window(object):
    def setupUi(self, Window):
        Window.setObjectName("Window")
        Window.resize(1115, 730)
        Window.setAcceptDrops(True)
        Window.setAutoFillBackground(False)
        self.lineEdit_ip = QtWidgets.QLineEdit(Window)
        self.lineEdit_ip.setGeometry(QtCore.QRect(70, 20, 161, 20))
        self.lineEdit_ip.setObjectName("lineEdit_ip")
        self.btn_test_invoke = QtWidgets.QPushButton(Window)
        self.btn_test_invoke.setEnabled(True)
        self.btn_test_invoke.setGeometry(QtCore.QRect(930, 680, 75, 23))
        self.btn_test_invoke.setObjectName("btn_test_invoke")
        self.btn_invoke = QtWidgets.QPushButton(Window)
        self.btn_invoke.setGeometry(QtCore.QRect(830, 680, 75, 23))
        self.btn_invoke.setObjectName("btn_invoke")
        self.label_ip = QtWidgets.QLabel(Window)
        self.label_ip.setGeometry(QtCore.QRect(40, 20, 31, 16))
        self.label_ip.setObjectName("label_ip")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Window)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 140, 1061, 521))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.text_params = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.text_params.setObjectName("text_params")
        self.verticalLayout_2.addWidget(self.text_params)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.text_result = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.text_result.setObjectName("text_result")
        self.verticalLayout_2.addWidget(self.text_result)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.func_params = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.func_params.setObjectName("func_params")
        self.horizontalLayout.addWidget(self.func_params)
        self.label_port = QtWidgets.QLabel(Window)
        self.label_port.setGeometry(QtCore.QRect(310, 20, 41, 16))
        self.label_port.setObjectName("label_port")
        self.lineEdit_port = QtWidgets.QLineEdit(Window)
        self.lineEdit_port.setGeometry(QtCore.QRect(340, 20, 101, 20))
        self.lineEdit_port.setObjectName("lineEdit_port")
        self.lineEdit_flag = QtWidgets.QLineEdit(Window)
        self.lineEdit_flag.setGeometry(QtCore.QRect(650, 20, 113, 20))
        self.lineEdit_flag.setObjectName("lineEdit_flag")
        self.label_flag = QtWidgets.QLabel(Window)
        self.label_flag.setGeometry(QtCore.QRect(570, 20, 81, 20))
        self.label_flag.setObjectName("label_flag")
        self.lineEdit_func = QtWidgets.QLineEdit(Window)
        self.lineEdit_func.setGeometry(QtCore.QRect(70, 70, 161, 20))
        self.lineEdit_func.setObjectName("lineEdit_func")
        self.label_func = QtWidgets.QLabel(Window)
        self.label_func.setGeometry(QtCore.QRect(20, 70, 41, 16))
        self.label_func.setObjectName("label_func")
        self.comboBox = QtWidgets.QComboBox(Window)
        self.comboBox.setGeometry(QtCore.QRect(330, 70, 331, 22))
        self.comboBox.setObjectName("comboBox")
        self.label = QtWidgets.QLabel(Window)
        self.label.setGeometry(QtCore.QRect(270, 70, 54, 21))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Window)
        self.label_3.setGeometry(QtCore.QRect(680, 70, 71, 21))
        self.label_3.setObjectName("label_3")
        self.cb_func_total = QtWidgets.QComboBox(Window)
        self.cb_func_total.setGeometry(QtCore.QRect(750, 70, 331, 22))
        self.cb_func_total.setObjectName("cb_func_total")
        self.label_4 = QtWidgets.QLabel(Window)
        self.label_4.setGeometry(QtCore.QRect(580, 112, 71, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Window)
        self.label_5.setGeometry(QtCore.QRect(20, 110, 71, 20))
        self.label_5.setObjectName("label_5")
        self.te_now = QtWidgets.QTimeEdit(Window)
        self.te_now.setGeometry(QtCore.QRect(20, 680, 161, 22))
        self.te_now.setWrapping(False)
        self.te_now.setReadOnly(True)
        self.te_now.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(23, 59, 59)))
        self.te_now.setTime(QtCore.QTime(21, 11, 33))
        self.te_now.setObjectName("te_now")
        self.font_box = QtWidgets.QSpinBox(Window)
        self.font_box.setGeometry(QtCore.QRect(860, 20, 42, 22))
        self.font_box.setObjectName("font_box")

        self.retranslateUi(Window)
        QtCore.QMetaObject.connectSlotsByName(Window)

    def retranslateUi(self, Window):
        _translate = QtCore.QCoreApplication.translate
        Window.setWindowTitle(_translate("Window", "Ice测试"))
        self.btn_test_invoke.setText(_translate("Window", "测试invoke"))
        self.btn_invoke.setText(_translate("Window", "调用"))
        self.label_ip.setText(_translate("Window", "IP:"))
        self.label_2.setText(_translate("Window", "调用返回:"))
        self.label_port.setText(_translate("Window", "port:"))
        self.label_flag.setText(_translate("Window", "Ice对象flag:"))
        self.label_func.setText(_translate("Window", "函数名:"))
        self.label.setText(_translate("Window", "最近调用:"))
        self.label_3.setText(_translate("Window", "文件中函数:"))
        self.label_4.setText(_translate("Window", "函数说明:"))
        self.label_5.setText(_translate("Window", "函数参数:"))
        self.te_now.setDisplayFormat(_translate("Window", "yyyy-MM-dd HH:mm:ss"))
