# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Window(object):
    def setupUi(self, Window):
        Window.setObjectName("Window")
        Window.resize(1115, 858)
        Window.setAcceptDrops(True)
        Window.setAutoFillBackground(False)
        self.widget_more = QtWidgets.QWidget(Window)
        self.widget_more.setGeometry(QtCore.QRect(10, 870, 1081, 31))
        self.widget_more.setObjectName("widget_more")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.widget_more)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(30, 10, 371, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.theme_dark = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.theme_dark.setObjectName("theme_dark")
        self.horizontalLayout_2.addWidget(self.theme_dark)
        self.theme_light = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.theme_light.setObjectName("theme_light")
        self.horizontalLayout_2.addWidget(self.theme_light)
        self.btn_more = QtWidgets.QPushButton(self.widget_more)
        self.btn_more.setGeometry(QtCore.QRect(480, 20, 75, 23))
        self.btn_more.setObjectName("btn_more")
        self.widget_main = QtWidgets.QWidget(Window)
        self.widget_main.setGeometry(QtCore.QRect(10, 20, 1091, 821))
        self.widget_main.setObjectName("widget_main")
        self.btn_invoke = QtWidgets.QPushButton(self.widget_main)
        self.btn_invoke.setGeometry(QtCore.QRect(870, 770, 75, 23))
        self.btn_invoke.setObjectName("btn_invoke")
        self.btn_test_invoke = QtWidgets.QPushButton(self.widget_main)
        self.btn_test_invoke.setEnabled(True)
        self.btn_test_invoke.setGeometry(QtCore.QRect(980, 770, 75, 23))
        self.btn_test_invoke.setObjectName("btn_test_invoke")
        self.te_now = QtWidgets.QLabel(self.widget_main)
        self.te_now.setGeometry(QtCore.QRect(20, 770, 201, 21))
        self.te_now.setObjectName("te_now")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.widget_main)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 170, 1061, 581))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.text_params = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.text_params.setObjectName("text_params")
        self.verticalLayout_2.addWidget(self.text_params)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.text_result = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.text_result.setObjectName("text_result")
        self.verticalLayout_2.addWidget(self.text_result)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.func_params = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.func_params.setObjectName("func_params")
        self.horizontalLayout.addWidget(self.func_params)
        self.label_5 = QtWidgets.QLabel(self.widget_main)
        self.label_5.setGeometry(QtCore.QRect(10, 130, 71, 20))
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.widget_main)
        self.label_4.setGeometry(QtCore.QRect(530, 130, 71, 20))
        self.label_4.setObjectName("label_4")
        self.font_size = QtWidgets.QLabel(self.widget_main)
        self.font_size.setGeometry(QtCore.QRect(840, 40, 61, 21))
        self.font_size.setObjectName("font_size")
        self.label_ip = QtWidgets.QLabel(self.widget_main)
        self.label_ip.setGeometry(QtCore.QRect(30, 40, 31, 16))
        self.label_ip.setObjectName("label_ip")
        self.label_func = QtWidgets.QLabel(self.widget_main)
        self.label_func.setGeometry(QtCore.QRect(10, 90, 41, 16))
        self.label_func.setObjectName("label_func")
        self.lineEdit_ip = QtWidgets.QLineEdit(self.widget_main)
        self.lineEdit_ip.setGeometry(QtCore.QRect(60, 40, 161, 20))
        self.lineEdit_ip.setObjectName("lineEdit_ip")
        self.label_3 = QtWidgets.QLabel(self.widget_main)
        self.label_3.setGeometry(QtCore.QRect(670, 90, 71, 21))
        self.label_3.setObjectName("label_3")
        self.lineEdit_func = QtWidgets.QLineEdit(self.widget_main)
        self.lineEdit_func.setGeometry(QtCore.QRect(60, 90, 161, 20))
        self.lineEdit_func.setObjectName("lineEdit_func")
        self.comboBox = QtWidgets.QComboBox(self.widget_main)
        self.comboBox.setGeometry(QtCore.QRect(320, 90, 331, 22))
        self.comboBox.setObjectName("comboBox")
        self.label_port = QtWidgets.QLabel(self.widget_main)
        self.label_port.setGeometry(QtCore.QRect(300, 40, 41, 16))
        self.label_port.setObjectName("label_port")
        self.label_flag = QtWidgets.QLabel(self.widget_main)
        self.label_flag.setGeometry(QtCore.QRect(560, 40, 81, 20))
        self.label_flag.setObjectName("label_flag")
        self.lineEdit_flag = QtWidgets.QLineEdit(self.widget_main)
        self.lineEdit_flag.setGeometry(QtCore.QRect(640, 40, 113, 20))
        self.lineEdit_flag.setObjectName("lineEdit_flag")
        self.label = QtWidgets.QLabel(self.widget_main)
        self.label.setGeometry(QtCore.QRect(260, 90, 54, 21))
        self.label.setObjectName("label")
        self.font_box = QtWidgets.QSpinBox(self.widget_main)
        self.font_box.setGeometry(QtCore.QRect(920, 40, 51, 22))
        self.font_box.setObjectName("font_box")
        self.cb_func_total = QtWidgets.QComboBox(self.widget_main)
        self.cb_func_total.setGeometry(QtCore.QRect(740, 90, 331, 22))
        self.cb_func_total.setObjectName("cb_func_total")
        self.lineEdit_port = QtWidgets.QLineEdit(self.widget_main)
        self.lineEdit_port.setGeometry(QtCore.QRect(330, 40, 101, 20))
        self.lineEdit_port.setObjectName("lineEdit_port")

        self.retranslateUi(Window)
        QtCore.QMetaObject.connectSlotsByName(Window)

    def retranslateUi(self, Window):
        _translate = QtCore.QCoreApplication.translate
        Window.setWindowTitle(_translate("Window", "Ice测试"))
        self.label_6.setText(_translate("Window", "主题:"))
        self.theme_dark.setText(_translate("Window", "黑暗"))
        self.theme_light.setText(_translate("Window", "明亮"))
        self.btn_more.setText(_translate("Window", "more"))
        self.btn_invoke.setText(_translate("Window", "调用"))
        self.btn_test_invoke.setText(_translate("Window", "测试invoke"))
        self.te_now.setText(_translate("Window", "TextLabel"))
        self.label_2.setText(_translate("Window", "调用返回:"))
        self.label_5.setText(_translate("Window", "函数参数:"))
        self.label_4.setText(_translate("Window", "函数说明:"))
        self.font_size.setText(_translate("Window", "文字大小:"))
        self.label_ip.setText(_translate("Window", "IP:"))
        self.label_func.setText(_translate("Window", "函数名:"))
        self.label_3.setText(_translate("Window", "文件中函数:"))
        self.label_port.setText(_translate("Window", "port:"))
        self.label_flag.setText(_translate("Window", "Ice对象flag:"))
        self.label.setText(_translate("Window", "最近调用:"))
